"""add_missing_tables_reports_qr_audit

Revision ID: 1f3d265025ac
Revises: j0k1l2m3n4o5
Create Date: 2025-11-22 12:48:17.717752

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1f3d265025ac'
down_revision: Union[str, None] = 'j0k1l2m3n4o5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='custom|lead_analysis|assessment_performance|conversion_funnel|ai_insights'),
    sa.Column('config', sa.JSON(), nullable=False, comment='\n        Report configuration:\n        {\n            "metrics": ["leads_total", "conversion_rate", "average_score"],\n            "filters": {\n                "date_range": {"start": "2024-01-01", "end": "2024-12-31"},\n                "status": ["new", "qualified"],\n                "score_range": {"min": 60, "max": 100}\n            },\n            "group_by": "status",  # status|industry|date|assessment\n            "visualization": "bar_chart",  # bar_chart|line_chart|pie_chart|table\n            "sort_by": "leads_total",\n            "sort_order": "desc"\n        }\n        '),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=True, comment='\n        Schedule configuration:\n        {\n            "frequency": "daily|weekly|monthly",\n            "day_of_week": 1,  # For weekly (0=Monday)\n            "day_of_month": 1,  # For monthly\n            "time": "09:00",\n            "timezone": "Asia/Tokyo",\n            "recipients": ["user@example.com"]\n        }\n        '),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='If true, visible to all users in tenant'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable name (e.g., '展示会2025')"),
    sa.Column('short_code', sa.String(length=10), nullable=False, comment='Unique 7-character code for short URL'),
    sa.Column('short_url', sa.String(length=255), nullable=False, comment='Short URL (e.g., https://dgnl.ds/abc123)'),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Style settings: color, logo_url, frame, size'),
    sa.Column('qr_code_image_url', sa.String(length=500), nullable=True, comment='S3/R2 URL for PNG image'),
    sa.Column('qr_code_svg_url', sa.String(length=500), nullable=True, comment='S3/R2 URL for SVG image'),
    sa.Column('scan_count', sa.Integer(), nullable=False, comment='Total number of scans'),
    sa.Column('unique_scan_count', sa.Integer(), nullable=False, comment='Number of unique scans (by session)'),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True, comment='Timestamp of last scan'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether QR code is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qr_codes_assessment_id', 'qr_codes', ['assessment_id'], unique=False)
    op.create_index('idx_qr_codes_enabled', 'qr_codes', ['enabled'], unique=False)
    op.create_index('idx_qr_codes_short_code', 'qr_codes', ['short_code'], unique=True)
    op.create_index('idx_qr_codes_tenant_id', 'qr_codes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_assessment_id'), 'qr_codes', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_short_code'), 'qr_codes', ['short_code'], unique=True)
    op.create_index(op.f('ix_qr_codes_tenant_id'), 'qr_codes', ['tenant_id'], unique=False)
    op.create_table('qr_code_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_code_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False, comment='Full user agent string'),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='Device type: mobile, tablet, desktop'),
    sa.Column('os', sa.String(length=100), nullable=True, comment='Operating system: iOS, Android, Windows, etc.'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='Browser: Safari, Chrome, Firefox, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IPv4/IPv6 address (should be hashed for privacy)'),
    sa.Column('country', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 country code'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='City name'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Approximate latitude'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Approximate longitude'),
    sa.Column('scanned_at', sa.DateTime(), nullable=False, comment='Timestamp when QR code was scanned'),
    sa.Column('assessment_started', sa.Boolean(), nullable=False, comment='Whether user started the assessment'),
    sa.Column('assessment_completed', sa.Boolean(), nullable=False, comment='Whether user completed the assessment'),
    sa.Column('lead_created', sa.Boolean(), nullable=False, comment='Whether a lead was created'),
    sa.Column('lead_id', sa.UUID(), nullable=True, comment='Associated lead if created'),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Session ID from cookie/localStorage'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qr_code_scans_analytics', 'qr_code_scans', ['qr_code_id', 'scanned_at'], unique=False)
    op.create_index('idx_qr_code_scans_lead_id', 'qr_code_scans', ['lead_id'], unique=False)
    op.create_index('idx_qr_code_scans_qr_code_id', 'qr_code_scans', ['qr_code_id'], unique=False)
    op.create_index('idx_qr_code_scans_scanned_at', 'qr_code_scans', ['scanned_at'], unique=False)
    op.create_index('idx_qr_code_scans_session_id', 'qr_code_scans', ['session_id'], unique=False)
    op.create_index(op.f('ix_qr_code_scans_qr_code_id'), 'qr_code_scans', ['qr_code_id'], unique=False)
    op.create_index(op.f('ix_qr_code_scans_scanned_at'), 'qr_code_scans', ['scanned_at'], unique=False)
    op.drop_index('idx_ai_usage_logs_created_at', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_logs_operation', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_logs_tenant_created', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_logs_tenant_id', table_name='ai_usage_logs')
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_operation'), 'ai_usage_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_tenant_id'), 'ai_usage_logs', ['tenant_id'], unique=False)
    op.alter_column('error_logs', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('error_logs', 'request_headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('error_logs', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('error_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_error_logs_correlation_id', table_name='error_logs')
    op.drop_index('idx_error_logs_created_at', table_name='error_logs')
    op.drop_index('idx_error_logs_endpoint', table_name='error_logs')
    op.drop_index('idx_error_logs_error_type', table_name='error_logs')
    op.drop_index('idx_error_logs_tenant_created', table_name='error_logs')
    op.drop_index('idx_error_logs_tenant_id', table_name='error_logs')
    op.drop_index('idx_error_logs_type_created', table_name='error_logs')
    op.create_index(op.f('ix_error_logs_correlation_id'), 'error_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_endpoint'), 'error_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.drop_index('ix_ga_integration_enabled', table_name='google_analytics_integrations')
    op.drop_index('ix_ga_integration_tenant_id', table_name='google_analytics_integrations')
    op.drop_constraint('uq_ga_integration_tenant', 'google_analytics_integrations', type_='unique')
    op.create_index(op.f('ix_google_analytics_integrations_enabled'), 'google_analytics_integrations', ['enabled'], unique=False)
    op.create_index(op.f('ix_google_analytics_integrations_id'), 'google_analytics_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_google_analytics_integrations_tenant_id'), 'google_analytics_integrations', ['tenant_id'], unique=True)
    op.drop_index('ix_industries_is_active', table_name='industries')
    op.drop_index('ix_industries_tenant_id', table_name='industries')
    op.drop_index('ix_topics_is_active', table_name='topics')
    op.drop_index('ix_topics_tenant_id', table_name='topics')
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.create_index('ix_topics_tenant_id', 'topics', ['tenant_id'], unique=False)
    op.create_index('ix_topics_is_active', 'topics', ['is_active'], unique=False)
    op.create_index('ix_industries_tenant_id', 'industries', ['tenant_id'], unique=False)
    op.create_index('ix_industries_is_active', 'industries', ['is_active'], unique=False)
    op.drop_index(op.f('ix_google_analytics_integrations_tenant_id'), table_name='google_analytics_integrations')
    op.drop_index(op.f('ix_google_analytics_integrations_id'), table_name='google_analytics_integrations')
    op.drop_index(op.f('ix_google_analytics_integrations_enabled'), table_name='google_analytics_integrations')
    op.create_unique_constraint('uq_ga_integration_tenant', 'google_analytics_integrations', ['tenant_id'])
    op.create_index('ix_ga_integration_tenant_id', 'google_analytics_integrations', ['tenant_id'], unique=False)
    op.create_index('ix_ga_integration_enabled', 'google_analytics_integrations', ['enabled'], unique=False)
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_endpoint'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_correlation_id'), table_name='error_logs')
    op.create_index('idx_error_logs_type_created', 'error_logs', ['error_type', 'created_at'], unique=False)
    op.create_index('idx_error_logs_tenant_id', 'error_logs', ['tenant_id'], unique=False)
    op.create_index('idx_error_logs_tenant_created', 'error_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_error_logs_error_type', 'error_logs', ['error_type'], unique=False)
    op.create_index('idx_error_logs_endpoint', 'error_logs', ['endpoint'], unique=False)
    op.create_index('idx_error_logs_created_at', 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_error_logs_correlation_id', 'error_logs', ['correlation_id'], unique=False)
    op.alter_column('error_logs', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('error_logs', 'response_body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('error_logs', 'request_headers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('error_logs', 'request_body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_usage_logs_tenant_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_operation'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.create_index('idx_ai_usage_logs_tenant_id', 'ai_usage_logs', ['tenant_id'], unique=False)
    op.create_index('idx_ai_usage_logs_tenant_created', 'ai_usage_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_ai_usage_logs_operation', 'ai_usage_logs', ['operation'], unique=False)
    op.create_index('idx_ai_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_qr_code_scans_scanned_at'), table_name='qr_code_scans')
    op.drop_index(op.f('ix_qr_code_scans_qr_code_id'), table_name='qr_code_scans')
    op.drop_index('idx_qr_code_scans_session_id', table_name='qr_code_scans')
    op.drop_index('idx_qr_code_scans_scanned_at', table_name='qr_code_scans')
    op.drop_index('idx_qr_code_scans_qr_code_id', table_name='qr_code_scans')
    op.drop_index('idx_qr_code_scans_lead_id', table_name='qr_code_scans')
    op.drop_index('idx_qr_code_scans_analytics', table_name='qr_code_scans')
    op.drop_table('qr_code_scans')
    op.drop_index(op.f('ix_qr_codes_tenant_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_short_code'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_assessment_id'), table_name='qr_codes')
    op.drop_index('idx_qr_codes_tenant_id', table_name='qr_codes')
    op.drop_index('idx_qr_codes_short_code', table_name='qr_codes')
    op.drop_index('idx_qr_codes_enabled', table_name='qr_codes')
    op.drop_index('idx_qr_codes_assessment_id', table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
